compatibility_date = "2024-12-05"
main = "src/index.ts"
name = "my-app"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMWQwMmY4OGEtZTYyZC00ODZiLTliNmItZWM1ZjAyNjUxYzkyIiwidGVuYW50X2lkIjoiODkwNmIxMTYxZDE0MmE3Yjg1MjU2NzNjZTNjODhlYzZiZmQwMmE0ODJlNDA1ZWNhYmNjMTNkODNjYjM2YTdjMCIsImludGVybmFsX3NlY3JldCI6ImZkNmRiZjhlLTgyY2QtNDU0OC1hNWE2LWJkNGRlMDFkMTM3MiJ9.vdMfwmI5JmH1xpqbyCXniaGnQy5Y1TgZSfEtcWrgNx4"
JWT_SECRET = "My-secret-key"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
